package com.tech.point_system._enum;

public enum NotificationType {
    WELCOME_NOTIFICATION,
    ALMOST_THERE_NOTIFICATION,
    CLIENT_RETENTION_NOTIFICATION,
    POINTS_EXPIRATION_NOTIFICATION,
    PROMOTION_NOTIFICATION,
    CUSTOM_NOTIFICATION
}